# Generated by Django 4.0.3 on 2022-03-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='images',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
