# Generated by Django 3.1.2 on 2022-04-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0003_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
